<?php
/**
 * @file
 * Drupal hooks
 */

/**
 * Implements hook_search_api_alter_callback_info().
 */
function bellcom_elasticsearch_exclude_unpublished_content_search_api_alter_callback_info() {
  $callbacks['bellcom_elasticsearch_exclude_unpublished_content_alter_settings'] = array(
    'name' => t('Bellcom Elastisearch exclude unpublished content'),
    'description' => t('Exclude unpublished content from indexing.'),
    'class' => 'SearchApiAlterExcludeUnpublishedContentAlterSettings',
  );
  return $callbacks;
}
