<?php
/**
 * @file
 * Drupal hooks
 */

/**
 * Implements hook_search_api_alter_callback_info().
 */
function bellcom_elasticsearch_parents_index_search_api_alter_callback_info() {
  $callbacks['bellcom_elasticsearch_parents_index_alter_settings'] = array(
    'name' => t('Bellcom Elastisearch Parents Index'),
    'description' => t('Add information about its parents to taxonomy terms.'),
    'class' => 'SearchApiParentsIndexAlterSettings',
  );
  return $callbacks;
}
