<?php
/**
 * @file
 * Code for the Acadre Postlister feature.
 */

include_once 'os2web_postlister.features.inc';

/**
 * os2web_postlister_feeds_after_parse
 * @return void
 * @author Henrik Farre <hf@bellcom.dk>
 **/
function os2web_postlister_feeds_after_parse(FeedsSource $source, FeedsParserResult $result)
{
  $fieldsToConvert = array(
    'journaldato',
    'dokumentdato'
    );

  foreach ($result->items as $key => $item)
  {
    foreach ($item as $itemKey => $itemData)
    {
      if ( in_array( strtolower( $itemKey ), $fieldsToConvert ) )
      {
        // Check if text format is used instead of Excel date format
        if (strpos($itemData,'-') !== FALSE) {
          // I don't trust strtotime if I don't know what timezone is
          list($day,$month,$year) = explode('-', $itemData);
          $result->items[$key][$itemKey] = mktime(0, 0, 0, $month, $day, $year);
        }
        else {
          // From: http://stackoverflow.com/a/15137007
          $convertedValue = ($itemData - 25569) * 86400;
          $result->items[$key][$itemKey] = $convertedValue;
        }
      }
    }
  }
}

/**
 * Implements hook_form_alter.
 */
function os2web_postlister_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == "postliste_import_node_form") {
    array_unshift($form['#validate'], 'os2web_postlister_form_replace_empty_source');
  }
}

/**
 * Helped funciton that replaces empty source in FeedsFileFetcher.
 *
 * Allows saving the node with empty file.
 */
function os2web_postlister_form_replace_empty_source($form, &$form_state) {
  if (empty($form_state['values']['feeds']['FeedsFileFetcher']['source'])) {
    $form_state['values']['feeds']['FeedsFileFetcher']['source'] = 'no file';
  }
}
