<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function bellcom_elasticsearch_clear_html_search_api_alter_callback_info() {
  $callbacks['bellcom_elasticsearch_clear_html_alter_settings'] = array(
    'name' => t('Bellcom Elastisearch Clear HTML'),
    'description' => t('Remove JSON and HTML tags from index'),
    'class' => 'SearchApiClearHTMLAlterSettings',
  );
  return $callbacks;
}  